# Generated by Django 5.0.3 on 2024-03-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('supply_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('supply_date', models.DateField()),
                ('stock_amt', models.PositiveBigIntegerField()),
                ('thumbnail', models.ImageField(upload_to='products')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
